export const GET_PLACES_REQUEST: string = "GET_PLACES_REQUEST"
export const GET_PLACES_SUCCESS: string = "GET_PLACES_SUCCESS"
export const GET_PLACES_ERROR: string = "GET_PLACES_ERROR"

export const GET_DROPDOWN_PLACES_REQUEST: string = "GET_DROPDOWN_PLACES_REQUEST"
export const GET_DROPDOWN_PLACES_SUCCESS: string = "GET_DROPDOWN_PLACES_SUCCESS"
export const GET_DROPDOWN_PLACES_ERROR: string = "GET_DROPDOWN_PLACES_ERROR"

export const GET_A_PLACE_REQUEST: string = "GET_A_PLACE_REQUEST"
export const GET_A_PLACE_SUCCESS: string = "GET_A_PLACE_SUCCESS"
export const GET_A_PLACE_ERROR: string = "GET_A_PLACE_ERROR"

export const SEARCH_LOGS_REQUEST: string = "SEARCH_LOGS_REQUEST"
export const SEARCH_LOGS_SUCCESS: string = "SEARCH_LOGS_SUCCESS"
export const SEARCH_LOGS_ERROR: string = "SEARCH_LOGS_ERROR"

export const AVAILABLE_LOGS_REQUEST: string = "AVAILABLE_LOGS_REQUEST"
export const AVAILABLE_LOGS_SUCCESS: string = "AVAILABLE_LOGS_SUCCESS"
export const AVAILABLE_LOGS_ERROR: string = "AVAILABLE_LOGS_ERROR"

export const ADD_SELECTED: string = "ADD_SELECTED"
export const REMOVE_SELECTED: string = "REMOVE_SELECTED"

export const SET_AVAILABLE: string = "SET_AVAILABLE"
export const REMOVE_AVAILABLE: string = "REMOVE_AVAILABLE"
